os: linux
sudo: required
language: c
services:
  - docker
arch: arm64
dist: bionic
env:
  - BASE=raspbian
  - BASE=debian64
script:
  - sudo docker build -t sfalexrog/qgc_builder -f Dockerfile.${BASE} .
after_script:
  - >
    if [ ! -z "$TRAVIS_TAG" ]; then
      echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin
      docker tag sfalexrog/qgc_builder sfalexrog/qgc_builder:${TRAVIS_TAG}-${BASE}
      docker push sfalexrog/qgc_builder:${TRAVIS_TAG}-${BASE}
    fi
